server:
  port: 8083

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:postgresql://localhost:5435/moviedb      # where to connect (JDBC connection string to postgres db)
    username: movie
    password: movie
    jpa:
      hibernate:
        ddl-auto: validate                            # Don't let Hibernate auto-create/change tables. (verify schema)
      properties:
        hibernate.jdbc.time_zone: UTC                 # Treat timestamps consistently in UTC
        hibernate.format_sql: true                    # Pretty-print SQL in logs for easier debugging
    flyway:
      enabled: true                                   # Turn Flyway on for this service (run versioned SQL at startup)
      locations: classpath:db/migration               # Where Flyway should look for migration files on the classpath (where V1__*.sql lives)


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics








#  /// REDUNDANT
#  /// NOW REPLACED WITH PROPER INGESTION SERVICE

#tmdb:
#  base-url: https://api.themoviedb.org/3
#  # api-key will come from environment (TMDB_API_KEY)
#
#movie:
#  tmdb:
#    seed:
#      enabled: false   # default: do NOT seed