spring:
  application:
    name: tmdb-ingestion-service
  main:
    web-application-type: none

tmdb:
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}
  api-key: ${TMDB_API_KEY}   # set via environment variable

movie-service:
  # local dev: localhost
  base-url: ${MOVIE_SERVICE_BASE_URL:http://localhost:8083}    # In docker, something like: http://movie-service:8083

ingestion:
  default-count: 50   # fallback if '--count=NN' not passed on the command line
  max-pages: 50

# To see debug logs (off for now)
#logging:
#  level:
#    com.microflix.tmdb_ingestion_service: DEBUG
