server:
  port: 8084

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:postgresql://localhost:5436/ratingdb      # where to connect (JDBC connection string to postgres db)
    username: rating
    password: rating
    jpa:
      hibernate:
        ddl-auto: validate                            # Don't let Hibernate auto-create/change tables. (verify schema)
      properties:
        hibernate.jdbc.time_zone: UTC                 # Treat timestamps consistently in UTC
        hibernate.format_sql: true                    # Pretty-print SQL in logs for easier debugging
    flyway:
      enabled: true                                   # Turn Flyway on for this service (run versioned SQL at startup)
      locations: classpath:db/migration               # Where Flyway should look for migration files on the classpath (where V1__*.sql lives)


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}


management:
  endpoints:
    web:
      exposure:
        include: health,info